name: DevSecOps CI/CD Pipeline

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:

  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest -v


  security:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install security tools
        run: |
          pip install bandit pip-audit

      - name: Run Bandit SAST scan
        run: bandit -r app -ll

      - name: Run dependency vulnerability scan
        run: pip-audit -r requirements.txt


  docker:
    name: Docker Build
    runs-on: ubuntu-latest
    needs: security

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t devsecops-platform:ci .


  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    needs: docker

    steps:
      - name: Deployment status
        run: echo "Secure deployment pipeline completed successfully."